[phases.setup]
nixPkgs = ["nodejs_20"]

[phases.build]
cmds = [
  "npm install",
  "npm run build"
]

[phases.start]
cmds = ["npm install --production=false", "npx vite preview --host 0.0.0.0 --port 3000"]

[start]
cmd = "npx vite preview --host 0.0.0.0 --port 3000"

[variables]
NODE_ENV = "production"
PORT = "3000"